# Generated by Django 5.2.11 on 2026-05-26 23:59

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('RESULT_VIEW', 'Result Viewed'), ('RESULT_QUERY', 'Result Queried'), ('REGISTRATION_CREATE', 'Registration Created'), ('REGISTRATION_UPDATE', 'Registration Updated'), ('MARKS_ENTRY', 'Marks Entered'), ('MARKS_APPROVAL', 'Marks Approved'), ('RESULT_RELEASE', 'Result Released'), ('RESULT_WITHHELD', 'Result Withheld'), ('ADMIN_ACTION', 'Admin Action')], max_length=30)),
                ('actor', models.CharField(blank=True, help_text='User or system that performed the action', max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('index_number', models.CharField(blank=True, help_text='Candidate index number if applicable', max_length=14)),
                ('description', models.TextField()),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=5, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Counties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExaminationYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('status', models.CharField(choices=[('REGISTRATION_OPEN', 'Registration Open'), ('REGISTRATION_CLOSED', 'Registration Closed'), ('EXAMINATION_ONGOING', 'Examination Ongoing'), ('MARKING_ONGOING', 'Marking Ongoing'), ('RESULTS_RELEASED', 'Results Released'), ('ARCHIVED', 'Archived')], default='REGISTRATION_OPEN', max_length=30)),
                ('registration_deadline', models.DateField(blank=True, null=True)),
                ('exam_start_date', models.DateField(blank=True, null=True)),
                ('exam_end_date', models.DateField(blank=True, null=True)),
                ('results_release_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='GradingScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('A', 'A'), ('A-', 'A Minus'), ('B+', 'B Plus'), ('B', 'B'), ('B-', 'B Minus'), ('C+', 'C Plus'), ('C', 'C'), ('C-', 'C Minus'), ('D+', 'D Plus'), ('D', 'D'), ('D-', 'D Minus'), ('E', 'E'), ('X', 'Absent/Cancelled')], max_length=3, unique=True)),
                ('points', models.PositiveIntegerField()),
                ('min_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'ordering': ['-points'],
            },
        ),
        migrations.CreateModel(
            name='ResultQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_number', models.CharField(max_length=14)),
                ('full_name_provided', models.CharField(max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('was_found', models.BooleanField(default=False)),
                ('queried_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-queried_at'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_code', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', '11-digit center code required')])),
                ('name', models.CharField(max_length=200)),
                ('school_type', models.CharField(choices=[('NATIONAL', 'National School'), ('EXTRA_COUNTY', 'Extra County'), ('COUNTY', 'County School'), ('SUB_COUNTY', 'Sub County School'), ('PRIVATE', 'Private School')], max_length=20)),
                ('category', models.CharField(choices=[('BOYS', 'Boys School'), ('GIRLS', 'Girls School'), ('MIXED', 'Mixed School')], max_length=10)),
                ('postal_address', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid Kenyan phone number e.g. +254712345678 or 0712345678.', regex='^\\+?254\\d{9}$|^0\\d{9}$')])),
                ('principal_name', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('subject_type', models.CharField(choices=[('COMPULSORY', 'Compulsory'), ('GROUP_1', 'Group 1 - Languages'), ('GROUP_2', 'Group 2 - Humanities'), ('GROUP_3', 'Group 3 - Sciences'), ('GROUP_4', 'Group 4 - Technical/Applied'), ('GROUP_5', 'Group 5 - Creativity/Arts')], max_length=20)),
                ('max_score', models.PositiveIntegerField(default=100)),
                ('has_practical', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_number', models.CharField(help_text='14-digit KNEC index number (11-digit center code + 3-digit student number)', max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='Index number must be a 14-digit code: 11-digit school code + 3-digit student number.', regex='^\\d{11}\\d{3}$')])),
                ('kcpe_index_number', models.CharField(help_text='KCPE index number from primary school', max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='KCPE index number must be 10–12 digits.', regex='^\\d{10,12}$')])),
                ('birth_certificate_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('full_name', models.CharField(help_text='Full name as it will appear on certificate', max_length=200)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(default='Kenyan', max_length=100)),
                ('passport_photo', models.ImageField(blank=True, null=True, upload_to='candidate_photos/')),
                ('has_special_needs', models.BooleanField(default=False)),
                ('special_needs_details', models.TextField(blank=True)),
                ('registration_status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted to School'), ('SCHOOL_VERIFIED', 'School Verified'), ('SUB_COUNTY_APPROVED', 'Sub County Approved'), ('COUNTY_APPROVED', 'County Approved'), ('KNEC_VERIFIED', 'KNEC Verified'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('examination_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='core.examinationyear')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='core.school')),
            ],
            options={
                'ordering': ['index_number'],
            },
        ),
        migrations.CreateModel(
            name='OverallResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_points', models.PositiveIntegerField(blank=True, null=True)),
                ('mean_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('subjects_sat', models.PositiveIntegerField(default=0)),
                ('subjects_counted', models.PositiveIntegerField(default=7)),
                ('school_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('sub_county_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('county_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('national_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PROVISIONAL', 'Provisional'), ('FINAL', 'Final'), ('WITHHELD', 'Withheld'), ('CANCELLED', 'Cancelled')], default='PROVISIONAL', max_length=15)),
                ('withheld_reason', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='overall_result', to='core.candidate')),
                ('examination_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.examinationyear')),
                ('mean_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overall_results', to='core.gradingscale')),
            ],
            options={
                'ordering': ['-total_points'],
            },
        ),
        migrations.CreateModel(
            name='SubCounty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_counties', to='core.county')),
            ],
            options={
                'verbose_name_plural': 'Sub Counties',
                'ordering': ['name'],
                'unique_together': {('county', 'name')},
            },
        ),
        migrations.AddField(
            model_name='school',
            name='sub_county',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools', to='core.subcounty'),
        ),
        migrations.CreateModel(
            name='CandidateSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.candidate')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
            ],
            options={
                'unique_together': {('candidate', 'subject')},
            },
        ),
        migrations.AddField(
            model_name='candidate',
            name='subjects',
            field=models.ManyToManyField(related_name='candidates', through='core.CandidateSubject', to='core.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together={('school', 'examination_year', 'kcpe_index_number')},
        ),
        migrations.CreateModel(
            name='SubjectResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('paper1_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('paper2_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('paper3_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('practical_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('raw_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('moderated_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('points', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Entry'), ('ENTERED', 'Marks Entered'), ('VALIDATED', 'Validated'), ('MODERATED', 'Moderated'), ('APPROVED', 'Approved'), ('WITHHELD', 'Withheld'), ('CANCELLED', 'Cancelled'), ('ABSENT', 'Absent')], default='PENDING', max_length=15)),
                ('withheld_reason', models.TextField(blank=True)),
                ('entered_by', models.CharField(blank=True, max_length=200)),
                ('entered_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=200)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_results', to='core.candidate')),
                ('examination_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.examinationyear')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.gradingscale')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
            ],
            options={
                'ordering': ['subject__code'],
                'unique_together': {('candidate', 'subject', 'examination_year')},
            },
        ),
    ]
